# Generated by Django 2.2.5 on 2019-10-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='password2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='userid',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
